#!/usr/bin/env python3
# SPDX-License-Identifier: MIT

import argparse
import hashlib
import json
import subprocess
from pathlib import Path

LICENSE_NAMES = ("LICENSE", "LICENSE.txt", "LICENSE.md", "COPYING", "NOTICE")
BUNDLED_COMPONENTS = (
    (
        "PackyMe privacy-filter detector code",
        "https://github.com/PackyMe/privacy-filter/commit/64b8de3c206059b187d65381189b70c267550392",
        "internal/privacyengine/LICENSE",
    ),
    (
        "ToS0 protocol-safe scanner adaptations",
        "https://github.com/ToS0/cpa-plugin-privacyfilter/commit/c2b9f3a5f662f6f378007c3389af4385d1c89bc5",
        "third_party/tos0.LICENSE",
    ),
    (
        "Gitleaks embedded rule snapshot",
        "https://github.com/gitleaks/gitleaks/commit/6eaad039603a4de39fddd1cf5f727391efe9974e",
        "third_party/gitleaks.LICENSE",
    ),
)


def decode_json_stream(text: str):
    decoder = json.JSONDecoder()
    offset = 0
    while offset < len(text):
        while offset < len(text) and text[offset].isspace():
            offset += 1
        if offset >= len(text):
            return
        value, offset = decoder.raw_decode(text, offset)
        yield value


def linked_modules(repo_root: Path):
    process = subprocess.run(
        ["go", "list", "-deps", "-json", "."],
        cwd=repo_root,
        check=True,
        stdout=subprocess.PIPE,
        text=True,
    )
    modules = {}
    for package in decode_json_stream(process.stdout):
        module = package.get("Module")
        if not module or module.get("Main"):
            continue
        while module.get("Replace"):
            module = module["Replace"]
        identity = (module.get("Path"), module.get("Version"))
        if not all(identity):
            raise SystemExit("linked dependency is missing a module path or version")
        modules[identity] = module
    return [modules[key] for key in sorted(modules)]


def license_files(module):
    root = Path(module["Dir"])
    files = []
    for name in LICENSE_NAMES:
        path = root / name
        if path.is_file():
            files.append(path)
    if not files:
        raise SystemExit(f"no root license file found for {module['Path']} {module['Version']}")
    return files


def normalized_text(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    return text.replace("\r\n", "\n").rstrip() + "\n"


def license_section(title: str, source: str, entries) -> str:
    lines = [f"## {title}", "", f"Source: {source}", ""]
    for label, text in entries:
        digest = hashlib.sha256(text.encode()).hexdigest()
        lines.extend(
            [
                f"### {label}",
                "",
                f"SHA-256: `{digest}`",
                "",
                "```text",
                text.rstrip(),
                "```",
                "",
            ]
        )
    return "\n".join(lines)


def generate(repo_root: Path) -> str:
    sections = [
        "# Third-party licenses",
        "",
        "This file is generated by `.github/scripts/generate-license-report.py` from",
        "the licenses of Go modules linked into the plugin and the explicitly bundled",
        "source/data components listed below. Do not edit it manually.",
        "",
    ]
    for module in linked_modules(repo_root):
        path = module["Path"]
        version = module["Version"]
        source = f"https://pkg.go.dev/{path}@{version}"
        entries = [(license_path.name, normalized_text(license_path)) for license_path in license_files(module)]
        sections.append(license_section(f"{path} {version}", source, entries))

    for title, source, relative_path in BUNDLED_COMPONENTS:
        license_path = repo_root / relative_path
        if not license_path.is_file():
            raise SystemExit(f"missing bundled license: {relative_path}")
        sections.append(license_section(title, source, [(relative_path, normalized_text(license_path))]))

    return "\n".join(sections).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=Path("THIRD_PARTY_LICENSES.md"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[2]
    output = args.output if args.output.is_absolute() else repo_root / args.output
    report = generate(repo_root)
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != report:
            raise SystemExit("third-party license report is not current")
        return
    output.write_text(report, encoding="utf-8")


if __name__ == "__main__":
    main()
